<?php

namespace EyesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * utilisateursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messageRepository extends EntityRepository
{
	  public function findAll()
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT f  FROM  EyesBundle:message f order by f.date_message desc"

        );

        //die(var_dump($query->getResult()));
       //var_dump($query->getResult());
         return $query->setMaxResults(10)->getResult();

        //return $query->getResult();
    }
}
